# Site settings:
# ---------------

title: Programvare . volleyball . no
description: Informasjon om programvare, spesielt for streaming, for norsk volleyball.
google_analytics: 
show_downloads: true
markdown: GFM
remote_theme: just-the-docs/just-the-docs

plugins:
  - jekyll-mentions

# Theme settings:
# ---------------

color_scheme: dark

aux_links:
  "volleyball.no":
    - "https://volleyball.no"
