# Site settings:
# ---------------

title: programvare.volleyball.no
description: Informasjon om programvare, spesielt for streaming, for norsk volleyball.
google_analytics: 
show_downloads: true
remote_theme: pmarsceill/just-the-docs

gems:
  - jekyll-mentions

# Theme settings:
# ---------------

color_scheme: dark

aux_links:
  "volleyball.no":
    - "https://volleyball.no"
